/*!
* Copyright (c) Microsoft Corporation.
* Licensed under the MIT License.
*/

export const strings = {
    appName: 'SandDance',
    bingsearch: 'Bing',
    bingsearchDescription: (term) => `"${term}"をBingで検索`,
    buttonClose: '閉じる',
    buttonSelect: '検索して選択',
    buttonColorSchemeMap: 'フィルタリングされたデータにカラースキームをマップ',
    buttonColorSchemeRemap: 'フィルタリングされたデータに色を再マップ',
    buttonColorSchemeKeep: '同じカラースキームを保持',
    buttonCopyToClipboard: 'クリップボードにコピー',
    buttonExclude: '除外',
    buttonExport: 'エクスポート',
    buttonExportCount: (total) => total == 1 ? '1行をエクスポート...' : `${total}行をエクスポート...`,
    buttonIsolate: '分離',
    buttonReset: 'フィルタリングを停止',
    buttonDeselect: '選択をクリア',
    buttonToolbarFloat: 'ツールバーをフロート',
    buttonToolbarDock: 'ツールバーをドック',
    buttonToolbarHide: 'ツールバーを隠す',
    buttonToolbarShow: 'ツールバーを表示',
    buttonNextDataItem: '次のデータ項目',
    buttonPrevDataItem: '前のデータ項目',
    buttonCreateSnapshot: 'スナップショットを作成',
    buttonNextSnapshot: '次のスナップショット',
    buttonPrevSnapshot: '前のスナップショット',
    buttonUpdateSnapshot: 'スナップショットを更新',
    buttonAddExpression: '式を追加',
    buttonAddExpressionGroup: 'グループを追加',
    buttonDeleteExpression: '削除',
    buttonDeleteExpressionGroup: 'グループを削除',
    buttonClearSnapshots: 'スナップショットをクリア',
    buttonDeleteSnapshot: 'スナップショットを削除',
    buttonEditSnapshot: 'スナップショットを編集',
    buttonMoveUp: '上に移動',
    buttonMoveDown: '下に移動',
    buttonShowVegaSpec: 'VegaSpecを表示',
    buttonLaunchVegaEditor: 'Vegaエディタを開く',
    buttonCameraHome: 'チャートをウィンドウの中心に',
    buttonTooltipMapping: 'ツールチップ列...',
    buttonBackgroundImage: '背景画像...',
    buttonTransitionReverse: '逆再生',
    buttonTransitionPause: '一時停止',
    buttonTransitionPlay: '再生',
    buttonUndo: '元に戻す',
    buttonRedo: 'やり直す',
    buttonColumnTypes: '列の種類...',
    buttonApply: '適用',
    buttonRemove: '削除',
    buttonResetToDefault: 'デフォルトにリセット',
    chartTypeBarChartH: 'バー',
    chartTypeBarChartV: 'カラム',
    chartTypeDensity: '密度',
    chartTypeGrid: 'グリッド',
    chartTypeScatterPlot: '散布図',
    chartTypeStacks: 'スタック',
    chartTypeStrips: 'ストリップ',
    chartTypeTreeMap: 'ツリーマップ',
    defaultFileName: 'sanddance-data',
    errorExportFilenameEmpty: 'ファイル名は空白にできません',
    errorExportFilenameCharacters: (characters) => `ファイル名には次の文字を含めることはできません: ${characters}`,
    errorColumnMustBeNumeric: 'このチャートタイプには数値列が必要です。',
    errorNumericValue: '値は数値でなければなりません',
    errorImageFormat: 'ファイルは画像ではありません',
    labelBackgroundImageDialogTitle: '背景画像',
    labelBackgroundImageSubtext: '背景画像は散布図、密度、スタックチャートでのみ表示できます。列は数値型でなければなりません。',
    labelBackgroundLeft: '左端',
    labelBackgroundRight: '右端',
    labelBackgroundBottom: '下端',
    labelBackgroundTop: '上端',
    labelBlank: '空白',
    labelNull: 'null',
    labelTrue: 'true',
    labelFalse: 'false',
    labelSystemInfo: 'システム情報',
    labelChangeColumnType: '列のタイプを変更',
    labelChartSettings: 'チャート設定',
    labelEditColumn: '編集',
    labelColumnName: '列名',
    labelColumnType: '列のタイプ',
    labelColumnDistinct: '異なる値',
    labelColumnHasColorData: '色データがあります',
    labelColumnIsColorData: '色データです',
    labelColumnQuantitativeMin: '最小',
    labelColumnQuantitativeMax: '最大',
    labelColumnQuantitativeMean: '平均',
    labelDataBrowser: 'データブラウザ',
    labelDataScope: 'スコープ',
    labelExport: 'データをエクスポート',
    labelExportFormat: 'ファイル形式',
    labelExportCSV: '.CSV - カンマ区切りの値',
    labelExportHTML: '.HTML - このデータを埋め込んだSandDanceのhtmlページ',
    labelExportJSON: '.JSON - JavaScriptオブジェクト表記',
    labelExportTSV: '.TSV - タブ区切りの値',
    labelHistory: '履歴',
    labelHistoryWarning: 'これにより現在の履歴が消去されます。',
    labelTools: 'ツール',
    labelHoldCamera: '前のカメラ位置を保持',
    labelVegaSpec: 'Vega仕様',
    labelColor: 'チャートの色',
    labelError: 'エラー',
    labelExportFileName: 'ファイル名',
    labelSnapshots: 'スナップショット',
    labelSnapshotSettingThumbnailWidth: 'サムネイル画像の幅',
    labelSearch: '検索による選択',
    labelSearchClause: '節',
    labelSearchColumn: 'フィールド',
    labelSearchOperator: '演算子',
    labelSearchValue: '値',
    labelSearchValuePlaceholder: '検索する値',
    labelChart: 'チャート',
    labelChartCanvas: 'チャートキャンバス',
    labelColumnMapping: '列マッピング',
    labelChartTypeOptions: 'チャートオプション',
    labelColorBin: '色のビニング',
    labelColorOptions: '色のオプション',
    labelColorBinExplanation: '数値列の場合',
    labelColorFieldInfo: (colorColumnName, colorColumnType, categoricalNumeric, distinctValueCount) =>
        `フィールド <span class="fieldname">${colorColumnName}</span> はタイプ <span class="fieldtype">${colorColumnType}</span>${categoricalNumeric ? ` であり、${distinctValueCount} の異なる値があります` : ''}。`,
    labelColorFieldIsColorData: (colorColumnName) =>
        `フィールド <span class="fieldname">${colorColumnName}</span> には直接の色データが含まれています。`,
    labelColorBinNone: 'なし（連続）',
    labelColorBinQuantize: '量子化',
    labelColorBinQuantile: '分位数',
    labelColorFilter: '注: このスナップショットを表示するときに、色はフィルターに再マップされます。',
    labelColorScheme: 'スキーム',
    labelTotal: '合計',
    labelTotalByCountSquare: 'カウント（グリッドレイアウト）',
    labelTotalByCountStrip: 'カウント（ストリップレイアウト）',
    labelTotalBySumStrip: '合計（ストリップレイアウト）',
    labelTotalBySumTreemap: '合計（ツリーマップレイアウト）',
    labelTotalBySumStripPercent: '合計をパーセンテージで（ストリップレイアウト）',
    labelColumnColor: '色',
    labelColumnFacet: 'ファセット',
    labelFacetLayout: 'ファセットレイアウト',
    labelFacetLayoutWrap: 'ラップ',
    // labelFacetLayoutHorizontal: 'Horizontal',
    // labelFacetLayoutVertical: 'Vertical',
    labelFacetLayoutCross: '⊞',
    labelColumnFacetV: 'クロスファセット',
    labelColumnSort: '並び替え',
    labelColumnX: 'X軸',
    labelColumnY: 'Y軸',
    labelColumnZ: 'Z軸',
    labelColumnSize: 'サイズ',
    labelColumnGroup: 'グループ化',
    labelAliasColor: '色',
    labelAliasFacet: 'ファセット',
    labelAliasFacetV: '垂直ファセット',
    labelAliasSort: '並び替え',
    labelAliasX: 'X軸',
    labelAliasY: 'Y軸',
    labelAliasZ: 'Z軸',
    labelAliasSize: 'サイズ',
    labelAliasGroup: 'グループ',
    labelDataItemIsFiltered: 'アイテムはビューからフィルタリングされています',
    labelHistoryInit: '初期ビュー',
    labelHistoryFilterClear: 'フィルターをクリア',
    labelHistoryFilterIExclude: 'フィルターを除外',
    labelHistoryFilterIsolate: 'フィルターを分離',
    labelHistoryChangeChartType: chart => `${chart}にチャートタイプを変更`,
    labelHistoryMapColumn: column => `${column}の役割をマップ`,
    labelHistoryUnMapColumn: column => `${column}の役割をアンマップ`,
    labelHistoryReviveSnapshot: 'スナップショットを復活',
    labelHistoryColorBin: '色のビニングを変更',
    labelHistoryDirectColor: '直接色を変更',
    labelRenderer: 'レンダラーの品質',
    labelRendererAdvancedDisabled: 'レンダラーの品質（このデバイスでは強化3Dモードはサポートされていません）',
    labelRendererBasic: '標準モード',
    labelRendererAdvanced: '強化3Dモード',
    labelRendererOptions: 'レンダラーオプション...',
    labelRendererOptionsDialogTitle: 'レンダラーオプション',
    labelRendererOptionsAntialias: 'アンチエイリアス',
    labelRendererOptionsBloom: 'ブルームハイライト（選択用）',
    labelRendererOptionsBloomIntensity: '強度',
    labelRendererOptionsDof: '被写界深度',
    labelRendererOptionsDofRange: '焦点範囲',
    labelRendererOptionsFxaa: 'アンチエイリアス',
    labelRendererOptionsShadow: '影',
    labelRendererOptionsSsao: 'スクリーンスペースアンビエントオクルージョン',
    labelShowLegend: '凡例を表示',
    labelShowAxes: '軸を表示',
    labelSnapshotTitle: 'タイトル',
    labelSnapshotDescription: 'メモ（オプション）',
    labelTooltipMapping: 'ツールチップ列',
    labelTransition: 'トランジション',
    labelTransitionOptions: 'トランジションオプション',
    labelTransitionScrubber: 'トランジションスクラバー',
    labelTransitionStaggerBy: 'スタガー',
    labelTransitionStaggerByOrdinal: 'データ順',
    labelTransitionStaggerByColumn: '列',
    labelTransitionStaggerByPosition: '軸位置',
    labelTransitionStaggerOptions: 'スタガーオプション',
    labelTransitionStaggerReverse: '逆',
    labelTransitionDurations: 'トランジションの期間',
    labelTransitionCamera: '2D / 3Dビュー',
    labelTransitionDuration: '期間',
    labelTransitionStagger: 'スタガー',
    labelVegaSpecData: 'データ参照',
    labelVegaSpecNotes: '注: Vegaでこれを可視化するためには、カラースキームを変更する必要があるかもしれません。',
    labelYes: 'はい',
    labelNo: 'いいえ',
    labelConfirmation: 'よろしいですか？',
    labelColumnTypes: '列のタイプ',
    loading: '読み込み中...',
    schemeCategorical: 'カテゴリカル',
    schemeCyclical: 'サイクリカル',
    schemeDiverging: 'ダイバージング',
    schemeDual: 'デュアル',
    schemeSequentialMultiHue: 'シーケンシャルマルチヒュー',
    schemeSequentialMultiHueDark: 'ダーク背景用',
    schemeSequentialMultiHueLight: 'ライト背景用',
    schemeSequentialSingleHue: 'シーケンシャルシングルヒュー',
    selectDataSpanAll: '全ての行',
    selectDataSpanFilter: 'フィルタリング済み',
    selectDataSpanSelection: '選択済み',
    selectVegaSpecDataNone: 'なし',
    selectVegaSpecDataInline: 'インライン - 警告: 大きなデータセットではブラウザ/クリップボードのメモリを大量に使用する可能性があります。',
    selectVegaSpecDataUrl: 'URL',
    record: (current, total) => `${current} / ${total}`,
    searchEQ: '=',
    searchNEQ: '<>',
    searchGT: '>',
    searchGTE: '>=',
    searchLT: '<',
    searchLTE: '<=',
    searchNULL: 'nullまたは空',
    searchIN: '含む',
    searchSW: 'で始まる',
    searchWHERE: '条件',
    searchAND: 'かつ',
    searchOR: 'または',
    selectAny: '-- 任意 --',
    selectNone: '-- なし --',
    selectNumeric: '数値',
    selectNonNumeric: 'カテゴリカル',
    selectDirectColor: '直接色',
    selectReference: '列マッピング',
    tooltipSearch: (column, value) => `'${column}'で"${value}"を検索するにはクリックしてください`,
    labelRequired: '必須',
    labelSystem: 'システム',
    labelViewType2d: '2Dで表示',
    labelViewType3d: '3Dで表示',
    labelDataColors: 'このデータ列にCSSカラー値が含まれている場合に有効化されます。',
    labelDataNullAll: 'データを読み込んでいます...',
    labelDataNullFiltered: '選択を行った後、上部のバーから<b>分離</b>または<b>除外</b>を選択してフィルタリングできます。',
    labelDataNullSelection: '選択は以下の方法で行えます: <ul><li>チャートの軸をクリックする</li><li>凡例をクリックする</li><li>検索する</li></ul>',
    labelZeroAll: 'データセットには行がありません。',
    labelZeroSearchResults: '検索に一致する行はありません。',
    signalGroups: [
        { prefix: 'Chart', label: 'チャートオプション' },
        { prefix: 'Mark', label: 'マークオプション' },
        { prefix: 'RoleColor', label: '色オプション' },
        { prefix: 'RoleFacet', label: 'ファセットオプション' },
        { prefix: 'RoleSort', label: 'ソートオプション' },
        { prefix: 'RoleX', label: 'X軸オプション' },
        { prefix: 'RoleY', label: 'Y軸オプション' },
        { prefix: 'RoleZ', label: 'Z軸オプション' },
        { prefix: 'Text', label: 'テキストオプション' },
        { prefix: '*', label: 'オプション' },
    ],
    percentValueFormat: (value: number) => `${value}%`,
};
